[tox]
envlist = py312
isolated_build = True

[testenv]
deps = pytest
commands = pytest {posargs:tests}

[testenv:format]
deps = black
commands = black --check src tests utils

[testenv:lint]
deps = flake8
commands = flake8 src tests utils

[testenv:typecheck]
deps = mypy
commands = mypy src utils
