[tox]
envlist = py310, py312
isolated_build = True

[flake8]
max-line-length = 130
extend-ignore = E203

[testenv]
deps = pytest
commands = pytest {posargs:tests}

[testenv:format]
deps = black
commands = black --check src tests utils

[testenv:lint]
deps = flake8
commands = flake8 src tests utils

[testenv:typecheck]
deps = mypy
       types-tqdm
commands = mypy src utils
